[phases.setup]
nixPkgs = ["python312", "gcc", "pango", "fontconfig", "freetype", "harfbuzz", "gdk-pixbuf", "libffi"]

[phases.install]
cmds = ["pip install -r requirements/prod.txt"]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
    "python manage.py migrate"
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload"

[variables]
DJANGO_SETTINGS_MODULE = "config.settings.prod"
PYTHON_VERSION = "3.12"
